name: scan_qr
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_screenutil: ^5.6.0
  flutter_bloc: ^8.1.1
  bloc: ^8.1.0
  equatable: ^2.0.5
  dartz: ^0.10.1
  shared_preferences: ^2.0.15
  dio: ^5.0.1
  get_it: ^7.2.0
  injectable: ^2.1.0
  retrofit: ^4.0.1
  json_annotation: ^4.7.0
  freezed_annotation: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.3.2
  json_serializable: ^6.5.4
  retrofit_generator: ^5.0.0
  injectable_generator: ^2.1.4
  freezed: ^2.0.3

flutter:

  uses-material-design: true

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/inter/Inter-Black.ttf
          weight: 900
        - asset: assets/fonts/inter/Inter-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/inter/Inter-Bold.ttf
          weight: 700
        - asset: assets/fonts/inter/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/inter/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/inter/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/inter/Inter-Light.ttf
          weight: 300
        - asset: assets/fonts/inter/Inter-ExtraLight.ttf
          weight: 200

